### ISSUE TITLE
500 Error in app despite working perfectly in the browser

### ISSUE THREAD

**Issue by moleisking** [julian-alarcon/prospect-mail#1]
We couldn't find a mailbox for this recipient. Either they don't have a mailbox or don't have a licence assigned.
cId: A47320C6CE194D4296FD6D19F6E326FB
app: Mail
st: 500
reqid: afd7cfe1-aff6-4ea6-9a56-75d00792863f
wsver: 15.20.1965.14
efe: VI1P18901CA0024
ebe: VE1PR08MB4781
et: ServerError
esrc: SessionData
err: Microsoft.Exchange.Clients.Owa2.Server.Core.OwaUserHasNoMailboxAndNoLicenseAssignedException
estack: null
ts: 06/06/2019 10:37:36

**Comment by moleisking** [comment]
It would be nice to have some debug info or a developer mode. I think this might have something to do with https, redirects etc.

**Comment by moleisking** [comment]
I have done some investigation, and we are using owa. If I change in the main-window-controller.js everything works fine.

const outlookUrl = "https://outlook.company.com/owa"; //"https://outlook.office.com/mail";

**Comment by moleisking** [comment]
I would be nice to be able to set const outlookUrl  in a config file

**Comment by rubenmachado** [comment]
I'm having an issue with the login process. After iserting the email, the next page stays in blank forever.

I've testes on Ubuntu 18.04, 19.10 and Linux Mint 19.2. All them shows the same error.

Any suggestion to fix this blank screen?

**Comment by JonasMelin** [comment]
I have the same problem as @rubenmachado. Using Ubuntu 19.10. Ends up with a white screen forever when I click "next" after entering my email address. Please let me know if there are any solutions for this. Thx

**Comment by julian-alarcon** [comment]
Please try the new version`snap install vlc --channel=edge`

**Comment by codergoblin** [comment]
+1 
Start the app and get a blank white screen. Nothing happens at all

System:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
prospect mail version:
` latest/stable:    0.2.0 2020-10-26 (10) 66MB -`

**Comment by abhi29tyagi** [comment]
Even I'm facing the same issue as mentioned by the others above. 
Once you click on the next, post entering your email address, then there would be no going forward or coming back. It just stays there with a blank screen and no error message at all.

**Comment by julian-alarcon** [comment]
Please try the last pre-release 0.3 https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by abhi29tyagi** [comment]
Thanks Julian, Its working now.

**Comment by alpiua** [comment]
White screen, not working after I changed my outlook password :(
My company is using basic auth while redirecting from the outlook login page, ending with 401 status code on my.company.com. 
After basic auth it redirects me to outlook.office365.com/owa 
What I can do ?
