### ISSUE TITLE
Login using Single Sign On is not working

### ISSUE THREAD

**Issue by paaland** [julian-alarcon/prospect-mail#104]
Apparently there has been an upgrade to prospect-mail snap version to 0.2 and it no longer starts on Fedora 32.
No errors, not nothing, no running process.

```
$ prospect-mail
$ 
```

Worked fine before the update.

**Comment by paaland** [comment]
I built the AppImage version locally and that works fine. Why not add the AppImage version to the release?

**Comment by daveola** [comment]
Same problem on Ubuntu 20.04

**Comment by julian-alarcon** [comment]
Please try the latest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by daveola** [comment]
Tried the v0.3.0 and it starts up a window, asks me to login as far as giving my email, and after I give my email address it just gives me a blank window with "Sign in to Outlook" at the top.

Maybe this isn't dealing with the redirection to my providers SSO?

**Comment by julian-alarcon** [comment]
Can you try the latest beta version?
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.4.0-beta

**Comment by daveola** [comment]
Sorry - I don't do snaps anymore, so I'll just use OWA unless Prospect releases a non-snap version.

**Comment by julian-alarcon** [comment]
There are pacman, Appimage, deb, rpm releases. https://github.com/julian-alarcon/prospect-mail/releases
And in the next version (0.4.0) there will be macOS and Windows versions too.

**Comment by julian-alarcon** [comment]
Also, check this possible workaround https://github.com/julian-alarcon/prospect-mail/issues/156#issuecomment-992486655
