### ISSUE TITLE
Publish pre-built assets

### ISSUE THREAD

**Issue by kisst** [julian-alarcon/prospect-mail#105]
Using the GH Actions https://github.com/actions/upload-release-asset this should be trivial, so in the releases page the deb, snap, Appimage asset can be hosted, next to the `zip`, and `tar.gz`

**Comment by galvianistudioeco** [comment]
Published on my fork https://github.com/MagiusCHE/prospect-mail

**Comment by mateMathieu** [comment]
Just a simple question, why are these releases not packaged as appimage, deb or rpm?
I don't want to use snap on my system. How should I do then?

**Comment by julian-alarcon** [comment]
Can you try another build instead of Snap available in the pre-release 0.3? https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0
