### ISSUE TITLE
Not Possible to print... Can find my print

### ISSUE THREAD

**Issue by Jonathanr67** [julian-alarcon/prospect-mail#107]
On ubuntu 20.04LTS i can't print any doc. I only can export in pdf on my desktop.

Do you have any solution ??

Thank you

**Comment by julian-alarcon** [comment]
I can see the normal dialog from the Operating System, so you should setup your printer in the OS first.
![image](https://user-images.githubusercontent.com/30119472/145814863-5dfea137-b86a-4d8f-a76d-6e53daa06ae6.png)

I will close this issue, please open a new one with information and screenshot of your issue if it's specific for this app.

**Comment by DaveEM** [comment]
I reproduced this issue after installing Prospect Mail  via the Snap Store. #204 is my proposed fix for this issue, but requires the commands below to be run until snapd is updated to eliminate these extra steps as described in the PR.

sudo snap install --edge cups 
snap connect prospect-mail:cups cups:cups

**Comment by julian-alarcon** [comment]
Merged changes from @DaveEM
