### ISSUE TITLE
Random Blank Screen causing need to remove and re-install

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#109]
Ubuntu 18.04 latest prospect-mail random white screen causing the need to have to remove and reinstall. Then works fine for a while.

Had 3 blank screens this week. Seem it might be related to Calendar handling because each time the blank window title is Calendar.

Also noticed this happens when trying to suggest an alternative time for a calendar request. I get a blank popup that has to be closed. This was working in previous version.

Cheers

**Comment by MagiusCHE** [comment]
Try my fork for leatest bugfix:  https://github.com/MagiusCHE/prospect-mail

**Comment by julian-alarcon** [comment]
Can you try another build instead of Snap available in the pre-release 0.3? https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0
