### ISSUE TITLE
Event does not load when viewing in a new window

### ISSUE THREAD

**Issue by nevadah-bfg** [julian-alarcon/prospect-mail#119]
Prospect Mail version 0.2.0 installed via Snap Store.

When an event is displayed in a new window from the My Day view, a new window opens but the event is never displayed. It appears to be trying to load the page; the word "Loading" appears with the spinning circle, but it remains in that state indefinitely.

Steps to reproduce:
1. Connect to an Office 365 account which contains events in its calendar, or add an event.
2. Display the email view.
3. Click My Day.
4. In the Calendar view in the My Day sidebar, click an event.
5. In the event view, click the icon to View full event in a new window.
Expected:
A new window opens and displays the detailed event information.
Actual:
A new window opens, but the event information is not displayed. Only the word "Loading" with the spinning circle is displayed.

Environment:
Linux Mint 20.04 with all updates applied as of time of writing.

**Comment by haukened** [comment]
Just verified this process.  This is fixed in PR #129 to properly support popout windows.
