### ISSUE TITLE
[ Feature Request ]  Showing the actual link address when hovering the pointer over links

### ISSUE THREAD

**Issue by alvarovm** [julian-alarcon/prospect-mail#122]
It would be useful to see the actual link address before we click in a link, this could help to identify fake addresses and malicious websites.
I also cannot copy the links and paste them in a browser.
thanks

**Comment by MagiusCHE** [comment]
Copy Done! It will be in the next PR #201
![immagine](https://user-images.githubusercontent.com/46496052/146260386-304471e2-e719-48e7-864a-24c18534a0be.png)
