### ISSUE TITLE
Reply All on a Calendar invite is not working

### ISSUE THREAD

**Issue by kartikbabu-bg** [julian-alarcon/prospect-mail#124]
When I right-click or double-click on an invite in my calendar and select the option to "Reply-All", it only opens a blank new window.

Running on Ubuntu 18.04

```
snap info prospect-mail

name:      prospect-mail
summary:   Unofficial Outlook client
publisher: Julian Alarcon (alarconj)
store-url: https://snapcraft.io/prospect-mail
contact:   https://github.com/julian-alarcon
license:   unset
description: |
  Unofficial Outlook client using Electron. It uses the Web App and wraps it
  as a standalone application using Electron.
  This inly works for Microsoft/Office 365 accounts, don't use it for
  personal Outlook.com accounts.
commands:
  - prospect-mail
snap-id:      ayYEnTUghgNUVwV5qAYugdfxikzAcSRM
tracking:     latest/stable
refresh-date: 2020-10-26
channels:
  latest/stable:    0.2.0 2020-10-26 (10) 66MB -
  latest/candidate: ↑                          
  latest/beta:      0.2.0 2020-10-27 (10) 66MB -
  latest/edge:      0.2.0 2020-10-26 (10) 66MB -
installed:          0.2.0            (10) 66MB -
```

**Comment by antonical** [comment]
I have exactly the same issue. On 18.04 and 20.04.

Cheers
Tony

**Comment by haukened** [comment]
So i'm looking into this, and it seems that there's something outlook specific thats not being passed to the child window; which causes the message not to load.
Please see this comment: https://github.com/jiahaog/nativefier/issues/408#issuecomment-378238680
Looks like this isn't unique to prospect mail, but the way that outlook works within electron.

**Comment by haukened** [comment]
so this appears to be solved by setting the main mail-window-controller webPreferences to have `nativeWindowOpen: true`
See this link for documentation: https://www.electronjs.org/docs/api/window-open#using-chromes-windowopen-implementation

I'll open a PR shortly.

**Comment by haukened** [comment]
This is addressed by PR #129
@julian-alarcon hoepfully you'll have time to review and merge a few of these.
the recent changes for updates, spellcheck, and popout PR's greatly increase usability.

**Comment by kartikbabu-bg** [comment]
Not ideal, but I do have a workaround: If you close that blank window, you'll see that a draft email has been created with all the correct recipients that you can open up and start editing.

**Comment by julian-alarcon** [comment]
Please try the lastest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by haukened** [comment]
i will give it a try!  

For anyone struggling running linux (or willing to make a launcher script for windows/mac) and doesn't require the system tray, running chrome like this gives you almost the same experience with no system tray (and no menu bar).

```
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Outlook
Exec=/usr/bin/google-chrome-stable --app=https://outlook.office365.com --new-window
```
(sub-in your server as required)
