### ISSUE TITLE
Application closes automatically after sometime 

### ISSUE THREAD

**Issue by PabitraPati** [julian-alarcon/prospect-mail#126]
Ubuntu 20.04 Focal

Open prospect mail app
Moved to terminal and continued my work on the terminal window
After sometime, the prospect-mail app found as Closed.

Clicking on the app, opens the app again and loads everything again.

**Comment by julian-alarcon** [comment]
Pleas try the latest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by PabitraPati** [comment]
On latest v 0.3.0 app doesn't closes anymore. Closing the ticket/

**Comment by PabitraPati** [comment]
On latest v 0.3.0 app doesn't closes anymore. Closing the ticket/
