### ISSUE TITLE
[Feature request] Won't let me login with my personal account 

### ISSUE THREAD

**Issue by ubuntu-pro** [julian-alarcon/prospect-mail#133]
I go on prospect mail and I signed in with my account but said "You can only login with school or work account"

**Comment by Marella139** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/53611626/110317501-82f52980-800c-11eb-9186-a3a4c03af2a6.png)

**Comment by julian-alarcon** [comment]
Please keep in mind that this client is only intended for Microsoft/Office 365 accounts. But, with the latest version you could add customUrl. Can you try them? https://github.com/julian-alarcon/prospect-mail#settings
Can you try the lastest pre-release 0.3? https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0
