### ISSUE TITLE
Notifications doesn't work on KDE Plasma

### ISSUE THREAD

**Issue by eirisdg** [julian-alarcon/prospect-mail#135]
In KDE Plasma, I cannot activate notifications:

![Screenshot_20210131_194104](https://user-images.githubusercontent.com/5367659/106394322-5f7f0380-63fc-11eb-81f0-d31bc2eeaeb2.png)

When use Chrome or Chromium, I can enable notifications in the same menu:
![image](https://user-images.githubusercontent.com/5367659/106394354-863d3a00-63fc-11eb-93c9-aae58c5df31b.png)

**Comment by zeitounator** [comment]
I think this can actually be extended and is probably related to the user agent used by electron. I can't see that setting either (i.e. "Desktop notifications") running on ubuntu 20.04 using gnome on Xserver.

**Comment by julian-alarcon** [comment]
Can you try the lastest pre-release 0.3? https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by AlexLevkovich** [comment]
it is the same with v. 0.3. When you are in browser it notifies by showing the notifications in the tab but I don't see any notifications with this application at all (neither internal ones in the tab nor the system ones).
