### ISSUE TITLE
Spell checker. 

### ISSUE THREAD

**Issue by davidRFB** [julian-alarcon/prospect-mail#139]
Hi ! Thank in advice you for the app. It is really useful. 

I am wondering if it is only my case, but I can not use the spell checker and correction tool, so maybe it is possible to allow some web browser app to work as a spell checker ? 

Best Regards,
David

**Comment by Michael-Hennemann** [comment]
Spell checking works for me fine - but "only" in English. 

As most of my emails are in German it would be nice to switch the spell checking to a different language...

**Comment by rsbelmont** [comment]
In this new release only English  is been underscored I would like to spell check it in portuguese. I tried chage the language and another location configuration but nothing. This is a great project lets help the developers this a realy good project.

**Comment by julian-alarcon** [comment]
Hi! Review your OS Language, also please test the latest version 0.4
