### ISSUE TITLE
Problem attaching a file from a mounted disk

### ISSUE THREAD

**Issue by leaorazio** [julian-alarcon/prospect-mail#14]
Je suis sous linux  (ubuntu gnome ), avec la version 01.1 de votre application. Lorsque je veux charger un fichier dans le cloud ou attacher un fichier a un mail, j'ai permision denied qui s'affiche. Pourtant tous les droits sont accordés sur ce répertoire.

**Comment by julian-alarcon** [comment]
Google translation (Please fill newer issues in English):
I am under linux (ubuntu gnome), with version 01.1 of your application. When I want to upload a file to the cloud or attach a file to an email, I have permission denied displayed. However, all rights are granted to this directory.

**Comment by julian-alarcon** [comment]
Please try the new version`snap install vlc --channel=edge`

**Comment by julian-alarcon** [comment]
No new info. If you still have this issue, please attach screenshots and more info. Thank you!
