### ISSUE TITLE
Application only starts with '--no-sandbox'

### ISSUE THREAD

**Issue by mikeyjk** [julian-alarcon/prospect-mail#140]
Hey there,

Firstly, thanks for this project, I'm excited to try this out.

I'm using Debian 10.8, with KDE, upon starting prospect-mail 'normally', I'm getting:
"Trace/breakpoint trap"

Given I'm using Debian and KDE it sounds a bit like this other issue:

- https://github.com/julian-alarcon/prospect-mail/issues/75
  - However I'm not having any issues during installation.
  - I also followed all the links provided and it really doesn't seem like my issue.
    - https://bugs.kde.org/show_bug.cgi?id=420431
      - I don't get an error running `update-desktop-database`
      - I don't have any MimeType's that reference \*/\*
    - https://github.com/clearlinux/distribution/issues/1906
      - This file doesn't exist for me (`/usr/share/applications/org.kde.kdeconnect_open.desktop`)
    - https://bugs.archlinux.org/task/65865
      - Seems to just be a tracker for the same mime type issue I don't seem to have

I've tried compiling the .deb from the repo directly after building, and I've tried using snap as well.

**Funnily enough, though, if I run prospect-mail with `--no-sandbox`, it starts up!**

Any suggestions?
Thanks all

**Comment by mikeyjk** [comment]
Just adding a note - since using with `--no-sandbox` this app has been amazing, it's immediately replaced my former calendar/mail client (evolution).

**Comment by julian-alarcon** [comment]
Please try the lastest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0 .

**Comment by mikeyjk** [comment]
```
$ prospect-mail 
Trace/breakpoint trap
```

Linux 7BFFRQ2 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux

Runs with `--no-sandbox`

**Comment by julian-alarcon** [comment]
Try
1. Removing the snap `sudo snap remove prospect-mail` then
2. Deleting the files located in `~/snap/prospect-mail`
3. And finally reinstall it with `sudo snap install prospect-mail`
