### ISSUE TITLE
App shows unreadable characters when downloading or uploading files to Prospect Mail

### ISSUE THREAD

**Issue by hassan-alhujhoj** [julian-alarcon/prospect-mail#143]
Here's an example for the bug.
![OutlookDownload-UploadBug](https://user-images.githubusercontent.com/71320802/110862693-88ac8100-8324-11eb-84b9-2162c82bb110.png)

**Comment by aaronbrighton** [comment]
I'm on Manjaro+Gnome3.

The only work around that worked for me was to use `/var/lib/snapd/snap/prospect-mail/current/prospect-mail` to open Prospect Mail.

To get the existing launcher icon to use this path instead I changed the symlink:

```
sudo mv /var/lib/snapd/snap/bin/prospect-mail /var/lib/snapd/snap/bin/prospect-mailbad
sudo ln -s /var/lib/snapd/snap/prospect-mail/current/prospect-mail /var/lib/snapd/snap/bin/prospect-mail
```

From what I could see online this is a common issue among Snap apps and no one seems to know why :man_shrugging:.

**_Disclaimer:_** I know almost nothing about Snap apps, and therefore have no idea what consequences this action may cause.  Do so at your own peril.

**Comment by julian-alarcon** [comment]
Seems to be similar to https://github.com/julian-alarcon/prospect-mail/issues/88.

Please try the lastest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0 . It has another builds (deb, rpb, pacman, appimage)

Also, can you provide the language set in your machine?

**Comment by aaronbrighton** [comment]
> Please try the lastest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0 . It has another builds (deb, rpb, pacman, appimage)
> 
> Also, can you provide the language set in your machine?

Confirmed I'm on v0.3.0 of the Snap.

Here's my locale configuration:

```
$ locale -a
C
de_DE.utf8
en_US.utf8
POSIX
$ locale 
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```
I've also seen this happen on draw.io's desktop app (which is also a Snap).

**Comment by julian-alarcon** [comment]
Duplicated of #88
