### ISSUE TITLE
Downloading attachment form the mail closes the application window.

### ISSUE THREAD

**Issue by PabitraPati** [julian-alarcon/prospect-mail#144]
Using prospect mail on Ubuntu.
Have received a mail with few attachments (Excel file to be specific)
Tried downloading the attachment from all three options shown below. 
But, from all of the above options, closes the mailbox entirely without downloading the application.

Download options - 
 1 - Select individual attachment and click on download icon.
 2 - Select individual attachment, click on Down arrow for More ACtions -> Select Download. 
 3 - Click on attachment for preview. ON top of preview window, select Download option. 
 4 - Click on  "Download All" below the list of attachments in the mail.

All the above options for downloading the attachment, Closes the mailbox without downloading the attachment.

**Comment by julian-alarcon** [comment]
Please try the lastest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0 .

**Comment by charlyeds** [comment]
Hi!!
for me, still crashes with v.0.3.
When I start snap app, it shows me this warning:

> (prospect-mail:16200): GdkPixbuf-WARNING **: 08:14:09.750: Cannot open pixbuf loader module file /home/user/snap/prospect-mail/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory`

When I try to download a n attachment:

> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/prospect-mail/15/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
> Aborted

Thanks!

**Comment by julian-alarcon** [comment]
Uninstall the snap application, then delete all the information related with the application, (`rm -rf ~/snap/prospect-mail/`) and try again.

Also, does it happens with any attachment? Or just Excel spreadsheets?

**Comment by charlyeds** [comment]
it works now!
thanks a lot

**Comment by PabitraPati** [comment]
Yes with latest Propsect Mail v0.3.0 this is no more seen, Works perfectly.

**Comment by Brulay-Man** [comment]
Hello. I had the same problem as the post opener.
v 0.3.0 working on Kubuntu 20.04 - 64 bits.
Made this and worked for me.

> Uninstall the snap application, then delete all the information related with the application, (`rm -rf ~/snap/prospect-mail/`) and try again.
> 
> Also, does it happens with any attachment? Or just Excel spreadsheets?

 I uninstalled and installed it again via _Discover_. Thank you, @julian-alarcon 



Hola. Tuve el mismo problema que el que comienza el hilo.
v 0.3.0 trabajando en Kubuntu 20.04 - 64 bits.
Hice esto y me funcionó:

> Desinstalar la aplicación snap, luego borrar toda la información relacionada con la aplicación, (`rm -rf ~/snap/prospect-mail/`) e intentar de nuevo.
> 
> Además, ¿sucede con cualquier archivo adjunto? ¿O sólo con las hojas de cálculo de Excel?

 Lo he desinstalado y vuelto a instalar a través de _Discover_. Gracias, @julian-alarcon
