### ISSUE TITLE
Gets stuck on Calendar tab or email tab 

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#151]
I am having an issue with prospect mail It was working until just recently. Then it appears to get stuck sometimes on the email view and you cannot switch to calendar or any other tab at the bottom left. There is a hover highlight when clicking  on them but nothing happens when you click.

The only answer I have found is to uninstall prospect mail snap remove the saved files and then re-install. But this issue then reappears seemingly at random (time and tab).

This is making the program unusable for my day to day usage.

As I said it was working fine. How to debug or provide further diagnostic information?

Cheers
Tony

**Comment by antonical** [comment]
Any ideas as to how to solve this problem other than continually removing and reinstall!

**Comment by Veldhoen** [comment]
I'm having the same issue, although for me just quitting the application (not only closing the window, but the app itself) and restarting it enables me to resolve it, until the issue randomly appears again. 
I also noticed that the hover highlight looks different (only the icon is highlighted, rather than the entire button) when it happens.

**Comment by adrianandrei-ca** [comment]
Same issue... Is there a log file anywhere?

**Comment by Veldhoen** [comment]
For me, the issue vanished after some time.
(I hope the same holds for you, Adrianandrei-ca)

**Comment by adrianandrei-ca** [comment]
Steps to reproduce:
- switch to Calendar view
- open an appointment (dbl click)
- click "Reply All"
- notice the participants are not pre-populated
- close the email without filling it
- close the opened appointment
- click event handler is gone at this point. Nothing "clicks" anymore :(

Steps to fix it:
- sudo snap remove prospect-mail
- sudo snap install prospect-mail

(Environment is Ubuntu 20.04)

**Comment by julian-alarcon** [comment]
Can you try the lastest pre-release 0.3? https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by alviboi** [comment]
I'm having the same issue with version 0.3.

**Comment by adrianandrei-ca** [comment]
In Ubuntu one can do:

killall -9 prospect-mail

And then click to start over.

**Comment by julian-alarcon** [comment]
Please install the latest version and cleanup your configuration. If you are using snap delete the directory `~/snap/prospect-mail` and then try again.
