### ISSUE TITLE
Logging out does not allow any kind of login. 

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#154]
If I log out then it display a logged out window but no option to login again or ever. Even restarting results in you are logged out window with no controls.

Only option is to remove and re-install

Cheers
Tony

**Comment by adrianandrei-ca** [comment]
Same here

**Comment by aaronbrighton** [comment]
If you kill the running Prospect Mail instance it will reset the login screen (so no need to uninstall/reinstall), but yes, slightly annoying (likely due to how the actual Microsoft 365 portal handles the logout, i.e. no redirect back to the login page).

**Comment by jtarbotton** [comment]
I would just like the close button to close the application so I don't have to use the kill.  Can't find setting to disable the close to minimize or any other way to close it.

**Comment by julian-alarcon** [comment]
This is a limitatin in the workflow of Microsoft Office 365.
You can use the **Quit** option from the tray icon to close the app completely and then reopen it, it will show you again the login screen.

**Comment by Morgma** [comment]
@julian-alarcon I think this is still a problem - I'm using Prospect on Manjaro/Gnome and this logout comes up every 12 hours or so when my MFA expires. Even clicking "Quit", the logout response persists. The only way to login again is killing the process.
