### ISSUE TITLE
404: Aw, snap! We couldn't find that page

### ISSUE THREAD

**Issue by aaronbrighton** [julian-alarcon/prospect-mail#161]
Looks like the Snapcraft listing has gone missing: https://snapcraft.io/install/prospect-mail/ubuntu

Any reason why?  If this is a permanent change, might be worth updating the README to remove references to the Snapcraft Store installation options.

**Comment by julian-alarcon** [comment]
Yeap, sorry about that, I'm managing an urgent change to fix a DMCA request from Microsoft... So, new icon!

**Comment by julian-alarcon** [comment]
It was restored! https://snapcraft.io/install/prospect-mail/
