### ISSUE TITLE
If you open a calendar event in fullscreen you can't close the calendar event

### ISSUE THREAD

**Issue by robby1212** [julian-alarcon/prospect-mail#17]
If you open a calendar event in fullscreen you can't close the calendar event you also cannot reset the app without drastic measures, i.e. reinstalling, rebooting etc.

Edit: I've only encountered this if I double click on a reminder. If I open an event on my calendar normally it doesn't open in an unclosable fullscreen. Also removing the ~/snap/prospect-mail folder fixes the issue.

**Comment by sam-sla** [comment]
If I open an event from the notifications it goes "fullscreen" inside the container window and I can't get out, the only say I know is to restart prospect-mail, but I never had to reset anything like that.
Would be nice to get this fixed though!

**Comment by donutsahoy** [comment]
I did notice that with the electron starter code if you just change the link to outlook.office.com it opens it in a new window. Wonder if it has to do with how the program is handling window creation?

**Comment by AZanoni1** [comment]
Running Linux Mint 19.   Selecting "Other reply actions -> Reply all by meeting" to reply to an email causes the same behaviour.  It leads to a window with no controls and no way back.

**Comment by julian-alarcon** [comment]
Solved with https://github.com/julian-alarcon/prospect-mail/pull/68 Thank you @donutsahoy !

**Comment by donutsahoy** [comment]
> Solved with #68 Thank you @donutsahoy !

Glad to help! Thank you for building such a helpful tool!
