### ISSUE TITLE
AUR support?

### ISSUE THREAD

**Issue by RandomExplosion** [julian-alarcon/prospect-mail#177]
Hello, I've got a small feature request. Is there any chance you could put this on the arch user repository?
Its a great piece of software but kinda annoying that you have to use a browser to get it. (or snap but we know how controversial that is). I would also prefer not to have to install snap to be able to use this.

EDIT: Just saw that there's a .pacman file, makes things easier but would still be really nice if you could just dump that file on the aur under `prospect-mail-bin` or something similar. I understand this probably isn't a massive priority.

**Comment by Dev727** [comment]
@RandomExplosion, I went ahead and made an [AUR package](https://aur.archlinux.org/packages/prospect-mail-bin/) of this. 

@julian-alarcon, you are definitely credited as the author of the package in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=prospect-mail-bin). Feel free to let me know if you're not OK with this. I just wanted to make it a bit easier on myself to install. :)

**Comment by RandomExplosion** [comment]
Awesome!, Tysm @Dev727!
