### ISSUE TITLE
Ctrl + not working 

### ISSUE THREAD

**Issue by Michael-Hennemann** [julian-alarcon/prospect-mail#178]
Hi, 
I am using the snap package on manjaro KDE and  pressed "ctrl -" to make the text smaller (works like in any browser to zoom out) 
unfortunately "ctrl +" is not working so my text is getting smaller and smaller and I cannot make it bigger again. Now I can't read anything :-|

any idea how to increase text size again ? :D 

cheers
Michael

**Comment by pablo8itall** [comment]
Use CTRL SHIFT and the PLUS key, the plus sign needs the shift key otherwise it is the equals sign on US/UK etc keyboards.

**Comment by Michael-Hennemann** [comment]
> 
> 
> Use CTRL SHIFT and the PLUS key, the plus sign needs the shift key otherwise it is the equals sign on US/UK etc keyboards.

Thanks! That worked !!!
