### ISSUE TITLE
White Blank Screen 

### ISSUE THREAD

**Issue by Colmanetti** [julian-alarcon/prospect-mail#180]
When I enter my work email address and click Next, I then see"Taking you to your organization's sign in page ...". But after go to blank white screen. My organization's require a login in external url . Maybe this is the problem ?

Is this something that is supported currently?

Thanks!

**Comment by Colmanetti** [comment]
Downloading the source , i can see what is the problem. I'm getting 401 from Request URL: https://adfs.bb.com.br/adfs/ls/wia?client-request-id=bb138609-94ba-dc18-3c7b-e865ce50a392&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAY2SP4zSYBjG-ShXjzPGizoYF41x8tLyff3Lh5pYyp-DEw4OuN4RE9KWthBovx60YnA3Dg4X4-TgoBujMcbgoLnxBsN8cTBOxElvchTi4qbP8DzP9ia_97lJIRalbsA_4pilM9C2EWNay_aXBhfW1uOPL36YPr_85fajufW58vrZBFztBIE_TCUSJAz6hPRYYttd02JN4ibISE-8B2AGwByASVSWeFmSJFFGyUUIPCdhlktCKJkiZgTECYwgWSKDRR4xtihjqQ0luy2jk-j5bSUMOtzSyKA7tk6jcZsM3JZPhsEL6i3I7Ic4QwqjvKLee0ACwzewzVSNLslkS-GWWuwccP3ifq5QKqcde3Mo82UE87Vcz8NOv-Q3s5msk1HKg1Ght1tU9pxGWqtUdb22pcLGbjqLdmpQlI0dJelgwfAO9vjeENuu2NL0fIkwWrZo9ztq7iEe63qYb7cbZamDw1agDethulYfdxHkg8VRHzouH1o2J5it7OaE-i_qbyh6gdIl3jFFE9_yuu1v1BUTcbKAoXi36wXWwCOsYSyBs8ZgFgNfY-B7LApXf8XAq5XFz34eqZOXT6vp6bujW837H8HxSsJFI3-oydhyN7RSkJS8cBSMSV0NeoYnbIxM16_7SClui75yR0yhQxoc0vSUjq9S65HrlFpBcxr8oMGTM5Fp_F8DOFm7xEEOMRAzMHkNwhTCKVFozs6CT-civwE1&cbcxt=&username=c1274905%40interno.bb.com.br&mkt=&lc=

@julian-alarcon do have any idea how to solve this ?

**Comment by julian-alarcon** [comment]
Duplicated of #156

**Comment by jdegiac** [comment]
I keep getting a white blank screen whenever I try and switch from my microsoft account to my gmail account. I have already signed in and lined it and everything
