### ISSUE TITLE
Readme file inconsistency

### ISSUE THREAD

**Issue by syul** [julian-alarcon/prospect-mail#187]
There is a list of main components described in readme file:

![image](https://user-images.githubusercontent.com/7660823/135966765-37746fdf-4144-413c-8f14-06f8aa8c5261.png)

In package.json we have next engine constraints:

![image](https://user-images.githubusercontent.com/7660823/135966859-51e181cc-d8ba-4f2f-ad44-d3589ccf5707.png)

So, could you please either update Readme file or package.json to make them consistent and not cause problems for people who try building the project using node version, specified in readme file.

**Comment by julian-alarcon** [comment]
Fixed in latest updates
