### ISSUE TITLE
Cannot attach any file that is on a mounted network share even though owned by my user

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#188]
Got some practical issues using this client.

Whenever I try to attach a file to an email. If that file is on a network share. Or is in a local directory that is linked to a network share I get an error stating. Could not read the contents of DIRECOTORY NAME  and error opening directory.

My user can use that directly fine generally and can read and write to the directory.

It is the same with any mounted network share.

The snap prospect-mail process appears to be running as my user.

I really need a solution for this as it is limited use without the ability to attach files. 

Cheers
Tony

Just a thought. Might this have something to do with AppArmor. As I am installing this application as a snap.

**Comment by antonical** [comment]
I really need a solution to this issue or some guidance on where to look to try and fix this. I even tried a new OOTB install of Ubuntu and installed prospect-mail same issue. Any drive that is a shared drive or a linked directory to a network folder I cannot work with files in that folder.

I have no issue in normal use and can read and write files in the folders that are networked.

Really need some help as otherwise this is painful having to copy files to a local folder and then attach them or save files from an email attachment locally and then having to copy them to the network.

Cheers
Tony

**Comment by antonical** [comment]
This is what I get when following the advice above:

sudo snap install prospect-mail --classic
Warning: flag --classic ignored for strictly confined snap prospect-mail

**Comment by julian-alarcon** [comment]
Hi!

Please try the latest 0.4.0 version. I was able to replicate the error using the 0.3.0 version
![image](https://user-images.githubusercontent.com/30119472/146037120-e1558fd7-fc14-437c-ab5e-1c4af03c6ea9.png)


And after using the latest 0.4.0 version (thanks to #198 ) it's working now and I'm able to attach files from USB/External devices. 
![image](https://user-images.githubusercontent.com/30119472/146037989-ada81de7-2037-457a-a122-b783e7abf3ce.png)


Maybe it also fixes the network attachments. Can you paste some screenshots of the error?

**Comment by antonical** [comment]
Sorry should have been clear. Appimage and deb was working with the 0.4.0 version. snap install prospect-mail --classic did not work.

Cheers
