### ISSUE TITLE
Start with `--startintray` or `--minimized`

### ISSUE THREAD

**Issue by manu0600** [julian-alarcon/prospect-mail#193]
Hi,

Is it possible to implement a `--startintray` feature ?
I frequently use the `Close to minimize` feature, and I would like to be able to run Prospect-Mail at startup without the window opening up, just run it minimized in the tray.

That would be amazing, thank you.

**Comment by MagiusCHE** [comment]
Added.

Waiting for pull-request to be merged, you can compile and use my fork.

https://github.com/MagiusCHE/prospect-mail

**Comment by julian-alarcon** [comment]
Fixed by https://github.com/julian-alarcon/prospect-mail/pull/197
