### ISSUE TITLE
[ Feature Request ] Add 'Refresh' to tray option

### ISSUE THREAD

**Issue by 0lzi** [julian-alarcon/prospect-mail#2]
Would be good to have a refresh button to reload the window. As there has been a few occasions where i have lost connection and not received any emails for hours but they appearing in Windows Outlook client and web.

Also on occasion selecting the menu in outlook web to access other office365 applications , page doesn't load and is just a blank screen so, a refresh to reset back to outlook would be beneficial.

Currently the workaround i am using is to select the 'Window Frame' and unchecking it, this reloads the page also.

**Comment by MagiusCHE** [comment]
Added to https://github.com/MagiusCHE/prospect-mail

**Comment by haukened** [comment]
This is addressed in PR #132 in case this dev wants to maintain upstream.

**Comment by julian-alarcon** [comment]
Fixed by https://github.com/julian-alarcon/prospect-mail/pull/132
