### ISSUE TITLE
Login required after restart - Ubuntu 21.10

### ISSUE THREAD

**Issue by bbijan** [julian-alarcon/prospect-mail#206]
After every restart/login into Ubuntu 21.10 (GNOME 40.4.0 Wayland) it prompts to login again.
It remembers the email but password has to be entered each time.

**Comment by Cherokee-Warrior** [comment]
Same issue as person above but I'm using linux mint 20.3 Una  (cinnamon)

**Comment by semlak** [comment]
Same problem on Ubuntu 22.04 LTS

**Comment by dmingledorff** [comment]
Same here.  22.04.

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.

**Comment by yermulnik** [comment]
@julian-alarcon I've just stumbled upon this issue as I was wondering whether Prospect Mail can remember password. I'm on 0.5.1 on Ubuntu 22.04. Please let me know if you'd prefer a new issue created. Thanks.
