### ISSUE TITLE
The applicattion gets freeze when you try to answer a mail that contains too much text in the body

### ISSUE THREAD

**Issue by fmajonei** [julian-alarcon/prospect-mail#207]
Steps to reproduce: 
1- Get an email with a lot of text and images on it. 
2- Click on Reply All
3- Start writing

Actual behavior: 
The application freeze and the words that you write don't appear on the screen. After a while, the letters appear altogether. 
You can't scroll down because the application becomes unresponsive.

**Comment by micw** [comment]
That happens to me almost always when I reply to a medium-large mail thread. I can type a whole sentence and wait ~30 seconds for it to appear.

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
