### ISSUE TITLE
[Bug] Click on embebbed image breaks right pane

### ISSUE THREAD

**Issue by pablorq** [julian-alarcon/prospect-mail#208]
Hi!

When an email has an embedded image and you click on it, the expected behavior is to have a sort of modal window to view the image, zoom it or download it.

Instead of this, the right pane gets gray and nothing makes it work again. You can select another email, hit esc or even close the window and reopen it again. The only thing that works is the option "Reload" form the tray icon.

Tested the same email+image on the browser (Firefox) and it works fine.

**Comment by catanzaromj** [comment]
Same issue here. Thanks for the "reload" tip from the tray, I've been exiting completely.

**Comment by AloneAndUnknown** [comment]
Same

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by catanzaromj** [comment]
Sorry @julian-alarcon I no longer use outlook-based email, so I can't try this.

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
