### ISSUE TITLE
Spelling 

### ISSUE THREAD

**Issue by cdstg** [julian-alarcon/prospect-mail#21]
I am using the SNAP how to get the spelling to work 
is there some other thing that needs to be installed ?

thanks

**Comment by jvacek** [comment]
https://github.com/electron/electron/pull/20692

**Comment by julian-alarcon** [comment]
Duplicated of: https://github.com/julian-alarcon/prospect-mail/issues/15

**Comment by fried-eggz** [comment]
> Duplicated of: #15

But #15 is Closed even though the issue persists

**Comment by fried-eggz** [comment]
Partial solution in #231
