### ISSUE TITLE
No icon in Ubuntu 21.10 dock

### ISSUE THREAD

**Issue by branttaylor** [julian-alarcon/prospect-mail#210]
When I open the app, the only icon that appears is I think a default generic icon instead of the prospect mail icon that i see in the tray. How do I properly set this to the app's icon?

OS: Ubuntu 21.10
Windowing system: Wayland
GNOME: 40.4.0

**Comment by datkira** [comment]
The same issue with **OS: Linux Mint 20.3** 
Try to walk through by changing the icon in _/usr/share/applications_ but it's not work correctly.

**Comment by FloHeinle** [comment]
@datkira this worked for me:
1. Download the prospect icon from the repo (https://github.com/julian-alarcon/prospect-mail/blob/main/assets/outlook_linux_black.png) 
2. move it under `/usr/share/icons` 
3. rename it to: `prospect-mail.png`

I am using gnome 41.3

**Comment by datkira** [comment]
> 

Thanks for your recommendation. It well works in Linux Mint 20.3 Cinnamon.

**Comment by datkira** [comment]
> @datkira this worked for me:
> 
> 1. Download the prospect icon from the repo (https://github.com/julian-alarcon/prospect-mail/blob/main/assets/outlook_linux_black.png)
> 2. move it under `/usr/share/icons`
> 3. rename it to: `prospect-mail.png`
> 
> I am using gnome 41.3

Thanks for your recommendation. It well works in Linux Mint 20.3 Cinnamon.

**Comment by branttaylor** [comment]
Great workaround @FloHeinle, this worked perfectly for me.

**Comment by Dev727** [comment]
Confirmed issue on Arch Linux as well. AUR package works, but no icon.

**Comment by Dev727** [comment]
This should be fixed in the next update. Based on [pr #211](https://github.com/julian-alarcon/prospect-mail/pull/211)

**Comment by quintanaplaca** [comment]
Hello.

> Download the prospect icon from the repo (https://github.com/julian-alarcon/prospect-mail/blob/main/assets/outlook_linux_black.png)
    move it under /usr/share/icons
    rename it to: prospect-mail.png

It worked fine for me. I've downloaded the `.deb` package:

`prospect-mail_0.4.0_amd64.deb`

For that, you can fix it.

**Comment by alexcorvis84** [comment]
> > @datkira this worked for me:
> > 
> > 1. Download the prospect icon from the repo (https://github.com/julian-alarcon/prospect-mail/blob/main/assets/outlook_linux_black.png)
> > 2. move it under `/usr/share/icons`
> > 3. rename it to: `prospect-mail.png`
> > 
> > I am using gnome 41.3
> 
> Thanks for your recommendation. It well works in Linux Mint 20.3 Cinnamon.

Thank you! I can confirm it works on Ubuntu 22.04.2 LTS as well :-) 

![image](https://user-images.githubusercontent.com/44984326/233014093-a8b679bf-23c3-464d-8188-130187adab11.png)
