### ISSUE TITLE
Turn off spell checking

### ISSUE THREAD

**Issue by SwampFalc** [julian-alarcon/prospect-mail#215]
While I fully understand that quite a few people were asking for a spell checker, I simply cannot use one that cannot be configured.

I work in Belgium for the government, with two official languages (Dutch and French). My laptop runs in English and at least some of my mails will be in that language too.

So I either need to be able to tell Prospect Mail that it should accept all three languages, or I would like a way to simply turn the whole spell check off. I can understand that a full configuration setup might take time, so some way to turn it off would be ideal in the short run.

**Comment by fried-eggz** [comment]
+1

**Comment by fried-eggz** [comment]
Any news on this?

**Comment by quintanaplaca** [comment]
Same here.

**Comment by julian-alarcon** [comment]
Newer version uses MS Editor spellchecker, languages are managed by your settings.
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by SwampFalc** [comment]
Small feedback: I am able to reach a settings page but cannot save any changes. Since I tried this with the full website as well and got the same result, I do not believe it is a prospect-mail issue but simply a MS issue. So this is mostly for information.
