### ISSUE TITLE
Copy and Past - Doesn't work

### ISSUE THREAD

**Issue by jreo** [julian-alarcon/prospect-mail#219]
After open a message, do not have copy and past using click with mouse.

**Comment by yakirm-cr** [comment]
I am also facing the same issue with version 0.4.0.
As a workaround, it is possible to select the text I want to copy, and press the keyboard combinations [Ctrl] + [Insert] or [Ctrl] + [C].

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
