### ISSUE TITLE
Fix Icon on Linux mint

### ISSUE THREAD

**Issue by Lahutsin** [julian-alarcon/prospect-mail#222]
Please. Fix Icon on Linux mint. 

![image](https://user-images.githubusercontent.com/104433304/165312652-84a6cc5a-d179-4b72-8e78-c4e622ffee54.png)

**Comment by kkmaslowski** [comment]
Also no icon on Fedora 35 (installed from RPM).

**Comment by kkmaslowski** [comment]
Quick fix: https://github.com/julian-alarcon/prospect-mail/issues/210#issuecomment-1033407695
```
wget https://github.com/julian-alarcon/prospect-mail/blob/main/assets/outlook_linux_black.png
sudo mv outlook_linux_black.png /usr/share/icons/rospect-mail.png
```

**Comment by julian-alarcon** [comment]
Duplicated of https://github.com/julian-alarcon/prospect-mail/issues/210
