### ISSUE TITLE
Interactions with Outlook (PWA) in Ubuntu

### ISSUE THREAD

**Issue by ber999** [julian-alarcon/prospect-mail#225]
As a result of interactions with Outlook (PWA) in Ubuntu, right window contents contentent is partly disabled.

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
