### ISSUE TITLE
In Ubuntu - no button for getting back from mail processing window to the initial window

### ISSUE THREAD

**Issue by ber999** [julian-alarcon/prospect-mail#226]
In Ubuntu - no button visible for getting back from mail processing window to the initial window,

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
