### ISSUE TITLE
Error MailBox Not Found

### ISSUE THREAD

**Issue by kevinsagen47** [julian-alarcon/prospect-mail#228]
My Organization uses a different method of signing in to Outlook, it takes me to the organization's own special sign in page.

![image](https://user-images.githubusercontent.com/36847106/170214021-b292ad4e-135b-4235-8c23-42ea0425b7e2.png)

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1
