### ISSUE TITLE
No notifications at all

### ISSUE THREAD

**Issue by shubham-cpp** [julian-alarcon/prospect-mail#230]
Hi here, I'm using this app with almost no issue and its good but 2 points are missing.
1. Any notification on new mails received
2. Any meeting reminders

OS: ArchLinux
App installed: [AUR](https://aur.archlinux.org/packages/prospect-mail-bin)
App version: 0.4.0-3
WM/Destops: DWM, Qtile, AwesomeWM, BSPWM, Xfce4

I've enabled notification 
![image](https://user-images.githubusercontent.com/31388020/172540187-f5b8f0ef-504f-4e0d-9fa3-c7dc087c1d55.png)

Is there something I'm missing?

**Comment by GerB** [comment]
Same here at Ubuntu with Gnome

**Comment by shubham-cpp** [comment]
@here Any updates?

**Comment by joelkay** [comment]
Same issue here, also installed via AUR

**Comment by micw** [comment]
Outlook usually contains a "desktop notification" area that is completely missing when shown from prospect mail. Maybe prospect is not announcing that browser-features?

![grafik](https://user-images.githubusercontent.com/186753/194834813-d69b8f19-0f07-4d9e-a9cd-3d282e12befa.png)

**Comment by mamaraddio** [comment]
Same issue, same installation method, same OS, DE KDE Plasma 5.26.4
@julian-alarcon

**Comment by NuclleaR** [comment]
any updates on this?

**Comment by thecijal** [comment]
I'am facing the same issue on Kubuntu 22.04 😞 

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-76-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics

I installed prospect-mail by `sudo snap install prospect-mail`.
![image](https://github.com/julian-alarcon/prospect-mail/assets/41804849/6b919bc8-7176-485a-bb5e-b6d272742c31)
