### ISSUE TITLE
Choose language for spell checker

### ISSUE THREAD

**Issue by fried-eggz** [julian-alarcon/prospect-mail#231]
Allow the user to set the language for the spell checker. It now only supports English

**Comment by cabildocl** [comment]
Hi, you can change the language in Preference ($HOME/snap/prospect-mail/current/.config/Prospect\ Mail/Preferences).
Example for use spanish:

{"spellcheck":{"dictionaries":["es"],"dictionary":""}}

**Comment by fried-eggz** [comment]
> Hi, you can change the language in Preference ($HOME/snap/prospect-mail/current/.config/Prospect\ Mail/Preferences). Example for use spanish:
> 
> {"spellcheck":{"dictionaries":["es"],"dictionary":""}}

Thanks. However, Prospect Mail does not seem to be installed in my $HOME/snap/ directory...

**Comment by fried-eggz** [comment]
Ok. Found the directory. But where to find dictionary for other languages?

In `$HOME/snap/prospect-mail/current/.config/Prospect\ Mail/Dictionaries/` there is only one file:

en-US-9-0.bdic

I updated my preference file to look like this, does it look correct?

`{"electron":{"media":{"device_id_salt":"3D8B24E94FC20067C15D1D3B479687C9"}},"spellcheck":{"dictionaries":["en-US", "sv-SE"],"dictionary":""}}`

**Comment by fried-eggz** [comment]
I've managed to partially solve the issue using the following steps:

1. Locate your Prospect Mail preferense folder:
- Rightclick the Prospect Mail icon in your taskbar and click "Settings -> Show settings file"

2. Edit the file "Preferences" and add you locale 
- Mine was Swedish so sv-SE
`{"electron":{"media":{"device_id_salt":"3D8B24E94FC20067C15D1D3B479687C9"}},"spellcheck":{"dictionaries":["en-US"**, "sv-SE"**],"dictionary":""}}`

3. Go to the folder `Dictionaries`

4. Copy your dictionary file to this folder
- You can get your language specific file by installing your langugae in Chrome/Chromium and copy it from `~/snap/chromium/common/chromium/Dictionaries`

5. Restart Prospect Mail

**Comment by fried-eggz** [comment]
Caveat: Still doesn't allow for Right-Click -> Correct spelling

**Comment by julian-alarcon** [comment]
New version uses MS Editor spellchecker, languages are managed by your settings.
