### ISSUE TITLE
Can not quit Prospect mail

### ISSUE THREAD

**Issue by RaviJain67** [julian-alarcon/prospect-mail#236]
SOEMTHING WENT WRONG - UNABLE TO QUIT

**Comment by RaviJain67** [comment]
![Screenshot from 2022-07-03 13-37-56](https://user-images.githubusercontent.com/108601415/177024191-206aa41f-f522-432c-a55c-9eadc8678041.png)

**Comment by anazia** [comment]
The way I resolved this @RaviJain67, is by adding this:
```
{
	"hideOnClose": false
}
```
to `.config/Prospect\ Mail/settings.json`

Basically, the app minimizes by default on Close, this that overrides that. (There is also a `hideOnMinimize` option if needed)

**Comment by julian-alarcon** [comment]
As mentioned, the expected behavior is to not close the app with the (x) of the window.
