### ISSUE TITLE
Blank window afeter internet connection lost while open then cannot get back to a functional app

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#237]
I   have just had an issue where I lost internet connection with prospect-mail open. I then had a black window with no controls apart from quit. 

After exit of the application and then restarting it. I just get a blank frame with no content. I tried removing the .deb and purging but on reinstall, I get the same issue.

Where is the config file or other data stored so I can get a clean install and start again? There must tbe some kind of config or state information left behind after uninstalling using APT or dpkg. I am having to use the online outlook currently.

Realy stuck. Any help appreciated.

Cheers
Tony

**Comment by antonical** [comment]
Had a few trys at cleaning the system. Ubuntu 22.04 to no avail every time I install it and open it I get a blank window. Like it is remembering its failed state before being uninstalled....

**Comment by julian-alarcon** [comment]
Hod did you installed the app? If it was using snap, please try this:
```
rm ~/.cache/fontconfig/*
~/snap/prospect-mail/
fc-cache -r
```

If you used apt, look for a directory/folder called `prospect-mail` in your ~/.cache and `/.config directories and delete it

**Comment by antonical** [comment]
Julian,

Thank you for this, it was the files in the .config directory that did the trick. 
Brilliant functional again.

Cheers
