### ISSUE TITLE
Spelling Check

### ISSUE THREAD

**Issue by quintanaplaca** [julian-alarcon/prospect-mail#238]
As mentioned in #15:

This is not fixed. Since there is no way to select a language, this only partially resolves the issue. If you use any other language than English you will get all your words underlined with no way to change language or turn the spellchecker completely off.

**Comment by fried-eggz** [comment]
How can this be closed since it still doesnt work?

**Comment by fried-eggz** [comment]
Again. This issue is closed and #15 is closed but the problem is still not fixed

**Comment by fried-eggz** [comment]
Partial solution in #231
