### ISSUE TITLE
Blank screen on open

### ISSUE THREAD

**Issue by Sachin7878** [julian-alarcon/prospect-mail#241]
![afdga](https://user-images.githubusercontent.com/22257773/181924493-9765cb86-3c30-4473-a82d-ae4e50a6f9fb.png)
Opening app shows blank screen, removing and installing again didn't help

**Comment by fried-eggz** [comment]
It will load if you wait about one minute. Definite bug though

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by arne-fuchs** [comment]
Got the same problem. Have no snap installed. Should I build it myself?

**Comment by julian-alarcon** [comment]
Can you try the latest 0.5.2 version available (.deb, AppImage, rpm, etc):
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.2

If you are using snap, you can also try the current beta channel:
sudo snap refresh prospect-mail --channel=beta

**Comment by arne-fuchs** [comment]
@julian-alarcon Thanks! It works again! Will also close https://github.com/julian-alarcon/prospect-mail/issues/304

**Comment by julian-alarcon** [comment]
Fixed by https://github.com/julian-alarcon/prospect-mail/pull/308
