### ISSUE TITLE
OWA is blocked by my organization. Only Mail Client is allowed. Is there a way Prospect Mail work as client?

### ISSUE THREAD

**Issue by cvakang** [julian-alarcon/prospect-mail#244]
My organization blocks webmail or OWA through browser. For Security reasons, Admins have blocked it. Is there a way the client can access emails other than OWA? I get the following error in browser as well

![image](https://user-images.githubusercontent.com/9618222/186037510-beff14a0-1f37-4199-b39f-bba86e47bac8.png)

**Comment by KPS-MWT** [comment]
Sorry, nothing you can do here. Prospect Mail is just a very nicely wrapped browser based on electron,

**Comment by julian-alarcon** [comment]
Ad mentioned above, there is no way to support your requirement. Sorry.
