### ISSUE TITLE
Prospect Mail absent from Snap Store

### ISSUE THREAD

**Issue by pkeir** [julian-alarcon/prospect-mail#247]
I've just installed Prospect Mail on Ubuntu 22.04 and I'm very happy with it.

I wanted to mentioned though that Prospect Mail doesn't appear in my Snap Store. (I was planning on viewing its reviews before installing.) I'm new to both Prospect Mail and Snap Store (normally a command-line snap user). If you think it should appear there, I can contact the Snap Store authors.

**Comment by pkeir** [comment]
Ok. Found it. It's under Social, rather than Productivity. (I wish the Snap Store had a search function.)

**Comment by julian-alarcon** [comment]
Snap Store installed in Ubuntu does has a you need to press Ctrl+F or click the left top button with a magnifier.
