### ISSUE TITLE
Settings are not remembered

### ISSUE THREAD

**Issue by ErwinBaeyens** [julian-alarcon/prospect-mail#249]
When closing Prospect Mail and later reopening it,  Prospect mail is not restoring all settings. 
Each time I restart my pc or prospect mail, I have to go to the view menu, and select layout in the ribbon and then set the folder pane to  be shown.  
After closing prospect mail  the view is changed back to not show the folder pane. 
Also the rightclick menu does not work. 

version used: 0.4.0
Operating system: Fedora Linux 36 Cinnamon version

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5.0-beta1)?
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
