### ISSUE TITLE
Prospect Opens but will not load any of my mail

### ISSUE THREAD

**Issue by jdegiac** [julian-alarcon/prospect-mail#254]

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)? Maybe was related to a bug with icons
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by jdegiac** [comment]
Just uninstalled and re-installed using the beta. It only happens when I switch from my Microsoft account to my Gmail account. The screen goes completely white. Is there an issue with loading Gmail accounts? (It does allow my to log in though)

**Comment by jdegiac** [comment]
That would be the default Microsoft account (I assume it sets a default because I did not create that Microsoft account)

**Comment by julian-alarcon** [comment]
I don't understand, Prospect only supports Microsoft accounts, no Gmail accounts. Do you mean a Microsoft account with a @gmail address? To be honest that's not a supported scenario.

**Comment by jdegiac** [comment]
Thank you for the information. Probably good to know as I was trying this with a gmail account.
