### ISSUE TITLE
Prevent prospect mail to open verfication url internally 

### ISSUE THREAD

**Issue by mrclemds** [julian-alarcon/prospect-mail#256]
My organization enforces the verification of any link you want to open.
The problem is that this verification is handled by an office.net endpoint which mean that prospect-mail tries to open it locally.

I can use the setting's `urlsExternal` array to enforce the exact domain name to be opened in my browser but as it's an office feature it would be great if included in the app so no need to have everyone do the set it up on their side.

What are your though about that ?

BTW in my case the FQDN to enforce external is `statics.teams.cdn.office.net`

**Comment by julian-alarcon** [comment]
This is currently supported.
Can you try with the latest beta version (0.5-beta1)? Maybe was related to a bug with icons
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1
