### ISSUE TITLE
Clicking link in email opened link in full-screen and I can't get back

### ISSUE THREAD

**Issue by seth-shaw-asu** [julian-alarcon/prospect-mail#265]
I clicked on a link in my email to an Airtable dashboard and it opened in the Prospect Mail window as full screen. Now I can't get back to my email. 

In case it matters, the email link was a urldefense.com (v3) version of the link and I had to use my organization's single sign-on to log into Airtable.

This appears to be similar to #17 but isn't resolved by #68.

**Comment by seth-shaw-asu** [comment]
I had to open my process manager, kill all the prospect-mail processes and then restart.

**Comment by seth-shaw-asu** [comment]
It doesn't appear that I can right-click and copy the URL to paste in a browser, nor does hovering over the link let me preview it.

**Comment by krlvo** [comment]
I have the same. Having a dedicated "back" button on my mouse helps to navigate, but it is not expected behaviour. Also the right click not working is very annoying.

**Comment by pkeir** [comment]
This may be the same issue discussed in #240 .

**Comment by julian-alarcon** [comment]
Duplicated of #240
