### ISSUE TITLE
Calls opened via Prospect are opened in the Chrome

### ISSUE THREAD

**Issue by seba7667** [julian-alarcon/prospect-mail#269]
When I am trying to join the call via the Prospect mail I am redirected to Chrome. The link is starting with [https://teams.m$.com/](https://teams.m%24.com/)....
I installed the newest teams for linux version available in the snap store.
I am using Ubuntu 22.04

**Comment by julian-alarcon** [comment]
I think that this is the intended behavior. Prospect Mail will not support videocalling features. If it's realted to MS Teams meetings I recommend and specific client for that: https://github.com/IsmaelMartinez/teams-for-linux
