### ISSUE TITLE
URL links & Right Click

### ISSUE THREAD

**Issue by Dunmarie** [julian-alarcon/prospect-mail#27]
First I want to say thanks for this program, I just love it.
I use Fedora 31 with Prospect Mail installed using Snap.
One problem I have found and maybe it is just a setting and not a problem is that links received in emails do not work. I do know it can be dangerous to click on such links if you don't know the sender, but that is why we have common sense. It shows as a link on Prospect Mail and when opening Outlook in a browser the links are working fine, just not in Prospect Mail.
The second issue is if you highlight something in the email body that you want to copy right click doesn't bring up the menu. You can click on ... and it will give you the menu, would just have been easier if right click works. Maybe another setting I have missed?
Thanks.

**Comment by julian-alarcon** [comment]
Tested with multiple cases, I see no issues in new version.
![Uploading image.png…]()

**Comment by asadmzmn** [comment]
Hi @julian-alarcon,
I use fedora 36 and see that the right click option in the mail body is not working. Is there any fix for this? Thanks

**Comment by mummyhen** [comment]
> Hi @julian-alarcon, I use fedora 36 and see that the right click option in the mail body is not working. Is there any fix for this? Thanks

Same on Ubuntu 20.04
