### ISSUE TITLE
repeating redirects

### ISSUE THREAD

**Issue by JSME4250** [julian-alarcon/prospect-mail#270]
whenever i log in it gives me an error 500 something went wrong repeating redirects detected and refreshing does not do anything

**Comment by ag-gaphp** [comment]
I'm having the same issue. Just curious why you closed this a day later, did you find a resolution? If so, it might help others to document what you did.

**Comment by JSME4250** [comment]
@ag-gaphp  My apologies, Putting it here did not cross my mind at the time.

The reason why this did not work for me was cause my account had too many roles. Since my Account is in Azure-AD and is being used my myself alone, I gave my account access to all roles (At the time i did not know about Global administrator role) so after removing all the roles and switching it with Global administrator, it worked perfectly fine (I do not think this is an error cause of Prospect Mail but rather from Microsoft their end).

I hope this information helps you.

**Comment by ag-gaphp** [comment]
@JSME4250 WOW... thank you. I can't believe something like that would cause so much ruckus, but reducing everything down to Global Administrator for my user not only fixed the prospect mail issue, but also my Betterbird/Thunderbird issues.

Thank you for the prompt reply, saved me a ton of headache! I was expecting to never be able to send email from my Arch machine.
