### ISSUE TITLE
special caracteres not working 

### ISSUE THREAD

**Issue by alansenairj** [julian-alarcon/prospect-mail#273]
I need to use portuguese br for this client. 
~ above is not working, like: ã õ 

How can I fix it?

**Comment by alansenairj** [comment]
Fedora 38 plasma KDE x11

**Comment by julian-alarcon** [comment]
I just tested it in the latest beta version, can you try that version?
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
