### ISSUE TITLE
0.4.0-beta rpm in Fedora installation has a conflict with draw.io package

### ISSUE THREAD

**Issue by alansenairj** [julian-alarcon/prospect-mail#275]
sudo dnf localinstall prospect-mail-0.4.0-beta.x86_64.rpm    
![image](https://github.com/julian-alarcon/prospect-mail/assets/20565821/0a156460-3a35-4e31-8055-6adaff9c7605)

**Comment by julian-alarcon** [comment]
Can you try the latest beta available here:
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1 ?

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
