### ISSUE TITLE
[FR] Pin to dash (favorite)

### ISSUE THREAD

**Issue by thob** [julian-alarcon/prospect-mail#276]
Can't find a way to elevate it as a favorite app, works with other Electron apps. I'm on Pop OS

**Comment by julian-alarcon** [comment]
Can you try with the latest beta version (0.5-beta1)? Maybe was related to a bug with icons
`sudo snap install prospect-mail --channel=beta`

Also available here in other packages: https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.0-beta1

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
