### ISSUE TITLE
URL should not open in message view

### ISSUE THREAD

**Issue by mmertama** [julian-alarcon/prospect-mail#279]
If email contains a link, that is opened in the message view.  If you open that from preview  - it occupies whole application window. And there is no way back!

If you close that window, it closes the Prospect emal, if you re-open app, it opens back to that window. Very annoying!

Sometimes only way I figured out is go Menu->New Window that let you open a app window again. Not intuitive at all. But what is worse: That is not always working. Sometimes you have to go click Prospect email icon with left button and open a New Window from there. 

Ubuntu 20.04

**Comment by robbertu** [comment]
Very annoying indeed. Also on Ubuntu 22.04.

**Comment by julian-alarcon** [comment]
Duplicated of #240
