### ISSUE TITLE
[Bug]: Can't attach files after latest update

### ISSUE THREAD

**Issue by dlahman** [julian-alarcon/prospect-mail#291]
**Describe the bug**
I just recently updated my prospect-mail snap and I can't attach any files. This worked as of last Tuesday, and the recent update may have broken the feature. Or maybe it's on Microsoft's side? Either way, I've tried a few different types of files (.pdf, .txt, .html) and they all fail to attach. The following is displayed above the `Send` button whenever I try to attach anything: 

> The following files couldn't be attached: myFile.txt. Please try again later. 

**To Reproduce**
1. Create any file
2. Open Prospect Mail
3. Create a new email 
4. Attempt to attach the file to the email

**Expected behavior**
Expected: The file should attach to the email draft. 
Result: Error message stating that the file couldn't be attached. 

**Screenshots**

![2023-09-22_16-10](https://github.com/julian-alarcon/prospect-mail/assets/15717294/5c49ccee-7721-45ad-9eb8-7d47fe608f1e)

**Desktop (please complete the following information):**

- OS: Linux Mint 21.2 Cinnamon
- Installation source: Snap 
- Version: 0.5.1 Rev 38, Tracking latest/stable

**Additional context**
Also, did you tried another build (AppImage, deb, rpm)?

**Comment by sedakrnt** [comment]
I was encountering an attachment error in the prospect mail, and I managed to resolve it by downgrading the version to 0.4.0. This solution worked effectively for me.
Download this package:
 https://github.com/julian-alarcon/prospect-mail/releases/download/v0.4.0/prospect-mail_0.4.0_amd64.deb

`cd ~/Downloads`
`sudo dpkg -i prospect-mail_0.4.0_amd64.deb`

**Comment by hdiamondlowe** [comment]
I also confirm this bug, same exact problem. 

OS: Ubuntu 20.04.6 LTS
Installation source: Snap

Downgraded to v0.4.0 as suggested by @sedakrnt and now attachments work again.

**Comment by pkeir** [comment]
I also confirm this bug on Ubuntu 23.04.

**Comment by mrjemson** [comment]
I also have this issue on Ubuntu 22.04 LTS.
I had to revert to 0.40

**Comment by ErwinBaeyens** [comment]
Same issue here Fedora 38 cinnamon spin
prospect-mail                         0.5.1                       38     latest/stable  alarconj       -

**Comment by niels-heinemann** [comment]
Same here on Ubuntu 23.10, latest Prospect Mail.

**Comment by Royal-Terrapin** [comment]
Same issue using Prospect Mail snap 0.5.1 on Xubuntu 22.04.03 LTS; will be downgrading Prospect Mail to 0.4 until this issue is resolved. 

Is there any way to sign up to receive a notification when this bug gets fixed?

**Comment by GreasyGoose19** [comment]
I had a similar issue with the login API of my company ChrisCross Solutions™. It took a lot of cross-functional effort and we were able to decrease the performance of our login API by about 25%. This allowed users to take additional time to enjoy other media or take care of personal items prior to accessing our software and award winning cross functional API. In today's dynamic, fast-paced and ever-evolving business ecosystem its more imperative than ever to synergize and leverage cutting-edge paradigms. The work that you have accomplished here with this bug fix is immensely impressive, and I would like to offer you a competitive salary and equity package at my startup. Please contact me at chriscrossapplesauce@gmail.com.

Thank you,
Chris
ChrisCross Solutions™

**Comment by julian-alarcon** [comment]
I found a possible solution for this issue, please try the latest 0.5.2 version available (.deb, AppImage, rpm, etc):
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.2

If you are using snap, you can also try the current beta channel:
`sudo snap refresh prospect-mail --channel=beta`

**Comment by hdiamondlowe** [comment]
Based on a quick test, this seems to have fixed the attachment problem. Thank you!

OS: Ubuntu 20.04.6 LTS
Installation source: Snap

**Comment by Royal-Terrapin** [comment]
Appears to work from Ubuntu 22.04.3 LTS running beta channel snap. Thank you!

**Comment by dlahman** [comment]
Thank you Julian! Really appreciate the fix here!

**Comment by julian-alarcon** [comment]
Still works for me @viggen66 
![image](https://github.com/julian-alarcon/prospect-mail/assets/30119472/6aa6ff89-bb81-4ab1-81b4-66240fa02e59)

**Comment by viggen66** [comment]
Julian spelling is working with your example after all, problem is on my side, gonna do a clean install, removing  .config/Prospect Mail to see if is fixed, btw thanks a lot for this project, one of a kind, of the best to keep linux desktop alive.
