### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dpalavra** [julian-alarcon/prospect-mail#298]
Can't attach files from "Browse the computer option"

1. Go to 'New Mail'
2. Attach a File
3. Browse computer

It should add a file to an email to be sent. It fails with the message: 
"The following files couldn't be attached: anyfile.pdf. Please try again later."

TRIED WITH MULTIPLE DIFFERENT FILES. It works if I go to my webmail, I can add the same files that are failing on Prospect. 

**Screenshots**

![Screenshot_20231003_110328](https://github.com/julian-alarcon/prospect-mail/assets/82952643/11248d85-e992-44a9-9873-41397c2377c8)
![Screenshot_20231003_110349](https://github.com/julian-alarcon/prospect-mail/assets/82952643/f4dad912-bbe0-4050-9b1b-228cc43268ab)

- OS: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
- Installation source: Snapstore
- Version e.g. 0.5.1, Latest

**Additional context**
Also, did you tried another build (AppImage, deb, rpm)?
I haven't.

**Comment by zeitounator** [comment]
I have the exact same problem. Are you on a custom company domain like I am ?

Unrelated: could you edit your issue and add a title ? thanks.

**Comment by zeitounator** [comment]
I strongly suspect the regression has been introduced by https://github.com/julian-alarcon/prospect-mail/commit/b0a7d6ed4b4a8dc00f7e037819ba511b1841d9d3 when changing the UserAgent.

**Comment by dpalavra** [comment]
Where did you find 0.4.9 version?

**Comment by zeitounator** [comment]
That was a typo, fixed above

**Comment by julian-alarcon** [comment]
Closed as duplicated of #291

**Comment by julian-alarcon** [comment]
I found a possible solution for this issue, please try the latest 0.5.2 version available (.deb, AppImage, rpm, etc):
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.2

If you are using snap, you can also try the current beta channel:
sudo snap refresh prospect-mail --channel=beta

**Comment by dpalavra** [comment]
Thank you sir! Tested, works!


***@***.***<https://www.appgate.com/>

Dzenan Palavra
Security Engineer, Information Security
Appgate

***@***.***<https://www.appgate.com/>

***@***.***<https://www.linkedin.com/company/appgate-security/>

***@***.***<https://twitter.com/AppgateSecurity>

***@***.***<https://www.youtube.com/channel/UC-8GvxcZbm-R3EJNl8jYjiQ>



***@***.***

M: +1 561.464.8824

________________________________
