### ISSUE TITLE
[Bug]: Titel Bar Missing

### ISSUE THREAD

**Issue by wKovacs** [julian-alarcon/prospect-mail#300]
Moin,

I use prospect-mail 0.5.1 on Ubuntu 23.04 with Gnome desktop. 

There is no title bar. I reinstalled via snap --purge but it did not help. Without the title bar moving the window and minimize is a hassle.

How do I get the title bar back?

Best

**Comment by julian-alarcon** [comment]
You probably disabled the show border option. Please go to the tray Icon and select the option: **Settings** -> **Show Window Frame**.
You can also remove it manually in the `settings.json` file, remove `"showWindowFrame":false`
