### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Denyaar** [julian-alarcon/prospect-mail#305]
**Describe the bug**
Failing to attach attachmnets.

**To Reproduce**
Try to attach anything 

![Screenshot from 2023-10-26 16-00-48](https://github.com/julian-alarcon/prospect-mail/assets/38788932/1fff32a0-95a7-49da-b849-3f4283746bfb)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu 22.04]-22.04
- Installation source: [deb, rpm, snap, AppImage, tar.gz, Snapstore]---snap
- Version [e.g. 0.5.0-beta1]

**Additional context**
Also, did you tried another build (AppImage, deb, rpm)?

**Comment by julian-alarcon** [comment]
Closed as duplicated of #291

**Comment by julian-alarcon** [comment]
I found a possible solution for this issue, please try the latest 0.5.2 version available (.deb, AppImage, rpm, etc):
https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.5.2

If you are using snap, you can also try the current beta channel:
sudo snap refresh prospect-mail --channel=beta
