### ISSUE TITLE
[Bug]: Prospect Mail does not open. Permission Denied while creating shared memory

### ISSUE THREAD

**Issue by viswans2132** [julian-alarcon/prospect-mail#336]
I have been using Prospect Mail on Ubuntu 20.04 for over two years. It was working fine except for a few crashes in the past. Recently, I reinstalled my OS and reinstalled Prospect-Mail. Now the app does not open. When I tried `prospect-mail` from my terminal, the following error appears. 

>(prospect-mail:7476): Gtk-WARNING **: 14:40:30.655: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name
>
>(prospect-mail:7476): Gtk-WARNING **: 14:40:30.658: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name
>
>(prospect-mail:7476): Gtk-WARNING **: 14:40:30.658: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
>[7476:0812/144030.697815:ERROR:platform_shared_memory_region_posix.cc(214)] Creating shared memory in /dev/shm/.org.chromium.Chromium.egvmT0 failed: Permission denied (13)
>[7476:0812/144030.697830:ERROR:platform_shared_memory_region_posix.cc(214)] Creating shared memory in /dev/shm/.org.chromium.Chromium.SYXH7j failed: Permission denied (13)
>Trace/breakpoint trap (core dumped)

I tried `sudo chmod 1777 /dev/shm` but that doesn't solve the issue. Could you please help me with this?

**Comment by dnet890** [comment]
this problem also happened on Ubuntu 24.04 as well for deb

**Comment by julian-alarcon** [comment]
Duplicated of #342
