### ISSUE TITLE
Cannot support Chinese display

### ISSUE THREAD

**Issue by yasenstar** [julian-alarcon/prospect-mail#34]
I install Prospect-mail via snap in deepin linux, it's display all Chinese characters as rectangle (unrecognized).
Even after I changed through OWA setting in Outlook, make the language into English (re-login), the header and menu characters are OK in English, but the mail title and mail content still not able to display Chinese characters.
Shall we supprot UTF-8? Or only Ansi?

Thanks.
Github: yasenstar

**Comment by julian-alarcon** [comment]
Can you share an screenshot with the issue? Also can you try the edge version? `snap install prospect-mail --channel=edge`

**Comment by elmolix** [comment]
I had the same problem, however, installing the edge version fixed the issue.

Thanks,

**Comment by yasenstar** [comment]
Hi Julian,

Thanks for your replying before. I switched to Ubuntu recently and just installed our Prospect Mail latest 0.2.0 from Snap Store, with default command `$ sudo snap install prospect-mail`, and have no issue of displaying double-byte characters in Outlook (with Office365). It's not an issue for me now. Thanks again.

Regards, Xiaoqi
