### ISSUE TITLE
Session keeper to avoid enforced sessions timeouts

### ISSUE THREAD

**Issue by the-lay** [julian-alarcon/prospect-mail#51]
Depending on the organization policy, session timeout can be sometimes set too low, see [this SE question](https://webapps.stackexchange.com/questions/115170/how-to-avoid-constant-logging-out-from-outlook-web-app).

The accepted answer suggests using some kind of session keeper / pinger, and proposes how to do this in Firefox. I'd be great to have this kind of functionality in Prospect Mail too.

**Comment by Orthopod666** [comment]
This would be very useful, since the forced log-out renders Prospect completely dead. The only way to get back to Outlook is to manually stop the Prospect threads and then restart Prospect. Right now, I only have a few minutes before Outlook logs out.

**Comment by julian-alarcon** [comment]
As a workaround, you could use the **Reload** option in the Tray icon Menu.

**Comment by ccGeo** [comment]
This is still an issue. 

Prospect stays open for me for about an hour, then a forced sign out occurs. 

Reload as suggested above does not work.

**Comment by julian-alarcon** [comment]
Closed as no response was given. Please create a new ticket with newer information if you experience a similar issue.
