### ISSUE TITLE
Clicking on a pop up notification leads to window with no controls and no way  back out

### ISSUE THREAD

**Issue by antonical** [julian-alarcon/prospect-mail#55]
Example. Pop up notification of a meeting. Click on it and it opens the event but with no window controls. No way out of this loop. Even if accepting the event  it then leads to blank window. Does not return to inbox view. Had t remove prospect-mail and then reinstall to start again.

**Comment by donutsahoy** [comment]
Same issue here. Easier way to fix this is to close Prospect Mail completely and then remove the prospect-mail in your local snap directory. i.e `~/snap/prospect-mail`

**Comment by julian-alarcon** [comment]
Duplicated https://github.com/julian-alarcon/prospect-mail/issues/17#issuecomment-638342916
