### ISSUE TITLE
Can't use hotmail.com address

### ISSUE THREAD

**Issue by ajgringo619** [julian-alarcon/prospect-mail#63]
Been using outlook.com for a long time after going through a ton of Linux apps that just never seemed to work that consistently. I was so excited to find this project...but it won't allow me to use a Hotmail account???

**Comment by julian-alarcon** [comment]
Sorry, this version is intended for the Office365 and MS Exchange. Please check this other project focused in Hotmail/Outlook.com personal accounts https://github.com/eNkru/freelook
