### ISSUE TITLE
Unable to login into Outlook

### ISSUE THREAD

**Issue by nutexan04** [julian-alarcon/prospect-mail#66]
I downloaded and installed the SNAP for Prospect Mail.  I have a personal outlook account not work or school.  When I attempt to login with Prospect Mail client: "You can't sign in here with a personal account. Use your work or school account instead."

![Screenshot from 2020-06-04 08-41-04](https://user-images.githubusercontent.com/47871734/83764427-8d2e6580-a63f-11ea-9b9d-67c9a6686a90.png)

**Comment by donutsahoy** [comment]
This is for Office 365 which means its for work or school accounts not for personal accounts.

**Comment by nutexan04** [comment]
Anything for use with personal accounts?

**Comment by donutsahoy** [comment]
It's electron, could just download the source code and modify the links in the `src/js/controllers/mail-window-controller.js` to point to regular office. ¯\_(ツ)_/¯
YMMV

**Comment by julian-alarcon** [comment]
Check this https://github.com/eNkru/freelook
