### ISSUE TITLE
No .exe or .dmg in downloads

### ISSUE THREAD

**Issue by Dev727** [julian-alarcon/prospect-mail#71]
Hi, 

I was just curious as to why there are no .exe or .dmg files in the download sections.

I have been able to build a .msi and .exe of the application and run it on Windows just as well as I have on Linux.

It's not so much an issue as it is a curiosity.

**Comment by julian-alarcon** [comment]
I tested .dmg file and it works fine. I will try the next days to include dmg and .exe but if you can help me to set this I'll be glad! (I will migrate from Travis-CI to Github Actions in a close future)
