### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by zour1el** [julian-alarcon/prospect-mail#75]
During install I get the error:
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)

I attempted to install 0.1.2 and 0.2.0-113

At launch I get Trace/breakpoint trap

I am running Kali Linux

**Comment by julian-alarcon** [comment]
Seems to be a KDE error:
https://bugs.kde.org/show_bug.cgi?id=420431
https://github.com/clearlinux/distribution/issues/1906
https://bugs.archlinux.org/task/65865
