### ISSUE TITLE
Add support for custom url

### ISSUE THREAD

**Issue by hovancik** [julian-alarcon/prospect-mail#77]
Add option to change `outlookUrl`, so we can use custom addresses.

**Comment by shubham2110** [comment]
@julian-alarcon  Is anyone working on this ? 

Creating a config file /etc/prospect-mail/pmail.conf file and reading values from there and overwrite outlookUrl value.

**Comment by MagiusCHE** [comment]
Custom url added on https://github.com/MagiusCHE/prospect-mail

**Comment by julian-alarcon** [comment]
Can you try another build instead of Snap available in the pre-release 0.3 https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0
