### ISSUE TITLE
[Feature request] Need a back button in Prospect Mail

### ISSUE THREAD

**Issue by hnnr145** [julian-alarcon/prospect-mail#78]
When any settings or anything is clicked, and the page is running with loading image, then there should be a chance to go back to previous view. Currently the outlook needs to be closed and opened again to see the mailbox view.

**Comment by luisrdzruiz** [comment]
I want this feature too

**Comment by julian-alarcon** [comment]
You can try the new **Reload** option in the latest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0

**Comment by julian-alarcon** [comment]
I will close this as multiple fixes has been deployed related with blank pages.
