### ISSUE TITLE
[Feature request] Resolution change (Zoom in and Zoom out)

### ISSUE THREAD

**Issue by marceloomoto** [julian-alarcon/prospect-mail#82]
It would be interesting to change screen resolution like using CTRL+(-/+) buttons on browser.
In my case, default screen allows only 1366x768 and everything seems too big, what reduces usability at all.

**Comment by gc-federico-lescano** [comment]
CTRL- appears to be working but not CTRL+. I am able to zoom out be not zoom in after. I have a 4k monitor and text is just too small for reading.

**Comment by julian-alarcon** [comment]
https://stackoverflow.com/questions/40262110/zoom-with-ctrlscroll-wheel-in-electron-app

**Comment by bkestelman** [comment]
The funny thing is CTRL SHIFT + works. Looks like this is a problem with electron: [https://github.com/electron/electron/issues/15496](https://github.com/electron/electron/issues/15496)

Supposedly they fixed it so maybe all that's needed is switching to a newer version?

**Comment by cbesangeeth** [comment]
This works for me 👇

Zoom In :    Ctrl Shift +
Zoom Out : Ctrl -

**Comment by julian-alarcon** [comment]
Thank you for this @cbesangeeth . It works for me too, so, I don't think this represents an issue anymore.
