### ISSUE TITLE
[Feature Request] Register as a default email app on ubuntu

### ISSUE THREAD

**Issue by pramodbutte** [julian-alarcon/prospect-mail#86]
Is it possible for this app to register itself as an email app in ubuntu 20.04 so that clicking on mailto: will open prospect mail and compose a message with the correct email address. 

An additional bonus feature, which will completely change the game will be use of prospect mail as a default email client, so when scheduling new meetings it will automatically open compose email with zoom details.

thanks

**Comment by julian-alarcon** [comment]
Duplicated of #33
