### ISSUE TITLE
Snap app fonts don't work

### ISSUE THREAD

**Issue by texasag99** [julian-alarcon/prospect-mail#88]
I'm trying to attach a document to an email but the fonts for the attach window are all squares and unreadable. I'm running prospect email using SNAP on an Arch Linux desktop environment. I've already tried clearing out the font-cache. Is there a specific font I need to install? please help..

![image](https://user-images.githubusercontent.com/6106731/92478463-2d9ca480-f1b0-11ea-91ae-4e7b416c6de5.png)

**Comment by julian-alarcon** [comment]
Please check this error with the new version available, 0.2

**Comment by ADeakin** [comment]
Just to confirm I get the same issue on 0.2.0 on Manjaro. Tried the edge version too and it's the same.

![WUx07Aj](https://user-images.githubusercontent.com/12967025/97979191-a2621880-1dc6-11eb-838d-5f43d913d449.png)

**Comment by negesti** [comment]
Same problem on a fres install of Fedora 33 with gnome-shell 33 both with Wayland and with X11. Worked previosly using an Fedora system that was upgraded from ~ 30 to 33

**Comment by aaronbrighton** [comment]
Also happening to me on Manjora/Arch.

**Comment by julian-alarcon** [comment]
Seems to be similar to #143.

Please try the lastest pre-release https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0 . It has another builds (deb, rpb, pacman, appimage)

Also, can you provide the language set in your machine?

**Comment by julian-alarcon** [comment]
There is a workaround. Please use the latest beta version  https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.4.0-beta and use the commands below

```sh
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
~/snap/prospect-mail/common/.cache/
fc-cache -r
```

This is a reported bug in snapcraft
https://forum.snapcraft.io/t/snaps-show-squares-instead-of-fonts/18073/9
https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/111
https://arcolinuxforum.com/viewtopic.php?t=1631

A possible fix is to use `core20` as base, but it seems to be still in development in electron-builder
https://github.com/electron-userland/electron-builder/issues/5257#issuecomment-985732948

**Comment by julian-alarcon** [comment]
I have the same issue in my local with the printing Dialog but not the Attach dialog.
If you have the same issue please post here the minimal information as: Operating System, Version of Prospect Mail used, package type (deb, rpm, snap, dmg, etc).

**Comment by julian-alarcon** [comment]
A new version 0.5-beta1 is available in the `beta` channel. Can you test it?
`sudo snap refresh prospect-mail --channel=beta`

**Comment by julian-alarcon** [comment]
Fixed updating to `core: 22` by: https://github.com/julian-alarcon/prospect-mail/commit/279ded9e8f6deeda728f97471972472d0bc9ca0e
