### ISSUE TITLE
Show me don't work

### ISSUE THREAD

**Issue by luisrdzruiz** [julian-alarcon/prospect-mail#89]
SO - Fedora 32
Prospect Version - 0.2.0

When the App is open and I click in show me option the window is close, when i click in show me again nothing pass.

**Comment by OnekO** [comment]
I have the same problem, using KDE Plasma 5.20.1

**Comment by gersondiesel** [comment]
Same problem for me. Debian Buster - Gnome Shell 3.30.2
I need to click on "Windows Frame" to activate again.

**Comment by haukened** [comment]
Good workaround @gersondiesel - i put in a PR to fix this, it was using `isFocused()` instead of `isVisible()` which causes unexpected behavior.

**Comment by eirisdg** [comment]
Same here
