### ISSUE TITLE
Is teams meeting supported in calendar mode ?

### ISSUE THREAD

**Issue by 3isenHeiM** [julian-alarcon/prospect-mail#91]
Is the "Teams meeting" creation available ?

Thanks

**Comment by julian-alarcon** [comment]
As far as I know, that's from own MS Outlook OWA experience.

Seems like it was recently deployed! (My new developer account doesn't have the option yet)
https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook

**Comment by futchas** [comment]
I only see the Skye option for meetings. Is it possible integrate MS Teams?
