### ISSUE TITLE
Non-Microsoft Exchange Servers

### ISSUE THREAD

**Issue by AdrianChallinorOsiris** [julian-alarcon/prospect-mail#93]
Prospect assumes it will connect to a Microsoft exchange server. If the email address is not found on Microsoft's servers, it should default to manual configuration and ask for a domain name..

**Comment by julian-alarcon** [comment]
As a workaround you can delete the folder with the snap settings.

**Comment by AdrianChallinorOsiris** [comment]
Thanks – I tried that. It made no difference. I can’t see away to do the manual setup I can do in Outlook, so I can’t specify the mail server address.

Adrian Challinor
Osiris Consultants Ltd
e: adrian.challinor@osiris.co.uk<mailto:adrian.challinor@osiris.co.uk>
t: +44-7860-290-883
w: https://www.osiris.co.uk

**Comment by MagiusCHE** [comment]
You can try use my fork and specify custom url instead.

https://github.com/MagiusCHE/prospect-mail

**Comment by AdrianChallinorOsiris** [comment]
Thank you. I am actually getting somewhere. I edited mail-window-controller.js and inserted my providers url, and I can get in.


Hat tip and virtual beer! 😊

________________________________

**Comment by julian-alarcon** [comment]
Can you try another build instead of Snap available in the pre-release 0.3? https://github.com/julian-alarcon/prospect-mail/releases/tag/v0.3.0
